
# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’
target 'Impact' do
pod 'CleverTap-iOS-SDK'


  # Uncomment the next line if you're using Swift or would like to use dynamic
  # use_frameworks!

  # Pods for Impact


  

end
